In [52]:
import pandas as pd
import numpy as np


df = pd.read_csv(r"C:\Users\User\PyCharmMiscProject\Datasets\Superstore_Data.csv")
df

      Order Date      Sales     Profit
0     17-10-2013  5175.1710   919.9710
1     07-11-2011  1822.0800   564.8400
2     14-04-2012  5244.8400   996.4800
3     06-06-2013  3701.5200  1036.0800
4     25-02-2012  1878.7200   582.3600
...          ...        ...        ...
5694  14-01-2013    38.9709   -32.3991
5695  12-11-2014     6.9000    -0.8400
5696  03-11-2011    17.2800   -13.9200
5697  26-07-2013    30.6180     1.0080
5698  19-08-2013     4.5600     0.0000

[5699 rows x 3 columns]

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5699 entries, 0 to 5698
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order Date  5699 non-null   object
 1   Sales       5699 non-null   float64
 2   Profit      5699 non-null   float64
dtypes: float64(2), object(1)
memory usage: 133.7+ KB

In [54]:
df["Order Date"] = pd.to_datetime(df["Order Date"], dayfirst=True)

In [55]:
df.sort_values(by=["Order Date"], inplace=True)
df.head()

     Order Date    Sales   Profit
5073 2011-01-01   55.242   15.342
3056 2011-01-01  120.366   36.036
4083 2011-01-01  113.670   37.770
424  2011-01-03  912.456 -319.464
5517 2011-01-03    6.006    0.546

In [56]:
df.tail()#so the data is 4 years

     Order Date     Sales   Profit
4875 2014-12-30    8.5407   2.3607
1455 2014-12-30  255.2850 -47.6550
4345 2014-12-30   10.8540  -6.6960
1804 2014-12-31  300.2400  84.0600
3956 2014-12-31   39.6000   6.6600

In [57]:
df.reset_index(drop=True, inplace=True)
df

     Order Date     Sales    Profit
0    2011-01-01   55.2420   15.3420
1    2011-01-01  120.3660   36.0360
2    2011-01-01  113.6700   37.7700
3    2011-01-03  912.4560 -319.4640
4    2011-01-03    6.0060    0.5460
...         ...       ...       ...
5694 2014-12-30    8.5407    2.3607
5695 2014-12-30  255.2850  -47.6550
5696 2014-12-30   10.8540   -6.6960
5697 2014-12-31  300.2400   84.0600
5698 2014-12-31   39.6000    6.6600

[5699 rows x 3 columns]

In [58]:
df.set_index("Order Date", inplace=True)#Explicit index when we add new index and implicit is when index is already exist index
df

               Sales    Profit
Order Date
2011-01-01   55.2420   15.3420
2011-01-01  120.3660   36.0360
2011-01-01  113.6700   37.7700
2011-01-03  912.4560 -319.4640
2011-01-03    6.0060    0.5460
...              ...       ...
2014-12-30    8.5407    2.3607
2014-12-30  255.2850  -47.6550
2014-12-30   10.8540   -6.6960
2014-12-31  300.2400   84.0600
2014-12-31   39.6000    6.6600

[5699 rows x 2 columns]

In [63]:
df.loc['2011-01-01'] #explicit index

              Sales  Profit
Order Date
2011-01-01   55.242  15.342
2011-01-01  120.366  36.036
2011-01-01  113.670  37.770

In [66]:
df.iloc[0:3] #implicit index

              Sales  Profit
Order Date
2011-01-01   55.242  15.342
2011-01-01  120.366  36.036
2011-01-01  113.670  37.770

In [69]:
df["2011-01" : "2011-02"].sum()

Sales     28622.5713
Profit     2330.1513
dtype: float64

In [70]:
df["2011" : "2012"].sum()

Sales     704488.6593
Profit     85321.5993
dtype: float64

In [ ]:
# the granularity rule => the more agg of forecast are more accurate it be
#